runtime: nodejs22

handlers:
  - url: /assets
    static_dir: dist/assets

  - url: /images
    static_dir: dist/images

  - url: /logos_prelaboral
    static_dir: dist/logos_prelaboral

  - url: /recursos_graficos
    static_dir: dist/recursos_graficos

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic