import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

# Inicializar la app con las credenciales
cred = credentials.Certificate("./utils/prelaboral-435211-edc2bbcab539.json")
firebase_admin.initialize_app(cred)

# Conectar a Firestore
db = firestore.client()

# Datos para casaEstudios
casa_estudios_data = [
    {"id": "usach", "nombre": "Universidad de Santiago de Chile", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Universidad", "fundacion": 1849},
    {"id": "uchile", "nombre": "Universidad de Chile", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Universidad", "fundacion": 1842},
    {"id": "puc", "nombre": "Pontificia Universidad Católica de Chile", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Universidad", "fundacion": 1888},
    {"id": "uaustral", "nombre": "Universidad Austral de Chile", "ciudad": "Valdivia", "region": "Región de Los Ríos", "tipo": "Universidad", "fundacion": 1954},
    {"id": "ucv", "nombre": "Universidad Católica de Valparaíso", "ciudad": "Valparaíso", "region": "Región de Valparaíso", "tipo": "Universidad", "fundacion": 1928},
    {"id": "udec", "nombre": "Universidad de Concepción", "ciudad": "Concepción", "region": "Región del Biobío", "tipo": "Universidad", "fundacion": 1919},
    {"id": "duocuc", "nombre": "Duoc UC", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Instituto Profesional", "fundacion": 1968},
    {"id": "inacap", "nombre": "INACAP", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Instituto Profesional", "fundacion": 1966},
    {"id": "udp", "nombre": "Universidad Diego Portales", "ciudad": "Santiago", "region": "Región Metropolitana", "tipo": "Universidad", "fundacion": 1982},
    {"id": "utalca", "nombre": "Universidad de Talca", "ciudad": "Talca", "region": "Región del Maule", "tipo": "Universidad", "fundacion": 1981}
]

# Datos para regiones
regiones_data = [
    {"id": "arica-parinacota", "nombre": "Región de Arica y Parinacota", "capital": "Arica"},
    {"id": "tarapaca", "nombre": "Región de Tarapacá", "capital": "Iquique"},
    {"id": "antofagasta", "nombre": "Región de Antofagasta", "capital": "Antofagasta"},
    {"id": "atacama", "nombre": "Región de Atacama", "capital": "Copiapó"},
    {"id": "coquimbo", "nombre": "Región de Coquimbo", "capital": "La Serena"},
    {"id": "valparaiso", "nombre": "Región de Valparaíso", "capital": "Valparaíso"},
    {"id": "metropolitana", "nombre": "Región Metropolitana de Santiago", "capital": "Santiago"},
    {"id": "ohiggins", "nombre": "Región del Libertador General Bernardo O'Higgins", "capital": "Rancagua"},
    {"id": "maule", "nombre": "Región del Maule", "capital": "Talca"},
    {"id": "nuble", "nombre": "Región de Ñuble", "capital": "Chillán"},
    {"id": "biobio", "nombre": "Región del Biobío", "capital": "Concepción"},
    {"id": "araucania", "nombre": "Región de La Araucanía", "capital": "Temuco"},
    {"id": "los-rios", "nombre": "Región de Los Ríos", "capital": "Valdivia"},
    {"id": "los-lagos", "nombre": "Región de Los Lagos", "capital": "Puerto Montt"},
    {"id": "aysen", "nombre": "Región de Aysén del General Carlos Ibáñez del Campo", "capital": "Coyhaique"},
    {"id": "magallanes", "nombre": "Región de Magallanes y de la Antártica Chilena", "capital": "Punta Arenas"}
]

# Datos para comunas (346 comunas completas)
comunas_data = [
    {"id": "arica", "nombre": "Arica", "regionId": "arica-parinacota"},
    {"id": "camarones", "nombre": "Camarones", "regionId": "arica-parinacota"},
    {"id": "putre", "nombre": "Putre", "regionId": "arica-parinacota"},
    {"id": "general-lagos", "nombre": "General Lagos", "regionId": "arica-parinacota"},
    {"id": "iquique", "nombre": "Iquique", "regionId": "tarapaca"},
    {"id": "alto-hospicio", "nombre": "Alto Hospicio", "regionId": "tarapaca"},
    {"id": "pozo-almonte", "nombre": "Pozo Almonte", "regionId": "tarapaca"},
    {"id": "caminia", "nombre": "Camiña", "regionId": "tarapaca"},
    {"id": "colchane", "nombre": "Colchane", "regionId": "tarapaca"},
    {"id": "huara", "nombre": "Huara", "regionId": "tarapaca"},
    {"id": "pica", "nombre": "Pica", "regionId": "tarapaca"},
    {"id": "antofagasta", "nombre": "Antofagasta", "regionId": "antofagasta"},
    {"id": "mejillones", "nombre": "Mejillones", "regionId": "antofagasta"},
    {"id": "sierra-gorda", "nombre": "Sierra Gorda", "regionId": "antofagasta"},
    {"id": "taltal", "nombre": "Taltal", "regionId": "antofagasta"},
    {"id": "calama", "nombre": "Calama", "regionId": "antofagasta"},
    {"id": "ollague", "nombre": "Ollagüe", "regionId": "antofagasta"},
    {"id": "san-pedro-atacama", "nombre": "San Pedro de Atacama", "regionId": "antofagasta"},
    {"id": "tocopilla", "nombre": "Tocopilla", "regionId": "antofagasta"},
    {"id": "maria-elena", "nombre": "María Elena", "regionId": "antofagasta"},
    {"id": "copiapo", "nombre": "Copiapó", "regionId": "atacama"},
    {"id": "caldera", "nombre": "Caldera", "regionId": "atacama"},
    {"id": "tierra-amarilla", "nombre": "Tierra Amarilla", "regionId": "atacama"},
    {"id": "chanaral", "nombre": "Chañaral", "regionId": "atacama"},
    {"id": "diego-de-almagro", "nombre": "Diego de Almagro", "regionId": "atacama"},
    {"id": "vallenar", "nombre": "Vallenar", "regionId": "atacama"},
    {"id": "alto-del-carmen", "nombre": "Alto del Carmen", "regionId": "atacama"},
    {"id": "freirina", "nombre": "Freirina", "regionId": "atacama"},
    {"id": "huasco", "nombre": "Huasco", "regionId": "atacama"},
    {"id": "la-serena", "nombre": "La Serena", "regionId": "coquimbo"},
    {"id": "coquimbo", "nombre": "Coquimbo", "regionId": "coquimbo"},
    {"id": "andacollo", "nombre": "Andacollo", "regionId": "coquimbo"},
    {"id": "la-higuera", "nombre": "La Higuera", "regionId": "coquimbo"},
    {"id": "paihuano", "nombre": "Paihuano", "regionId": "coquimbo"},
    {"id": "vicuna", "nombre": "Vicuña", "regionId": "coquimbo"},
    {"id": "illapel", "nombre": "Illapel", "regionId": "coquimbo"},
    {"id": "canela", "nombre": "Canela", "regionId": "coquimbo"},
    {"id": "los-vilos", "nombre": "Los Vilos", "regionId": "coquimbo"},
    {"id": "salamanca", "nombre": "Salamanca", "regionId": "coquimbo"},
    {"id": "ovalle", "nombre": "Ovalle", "regionId": "coquimbo"},
    {"id": "combarbala", "nombre": "Combarbalá", "regionId": "coquimbo"},
    {"id": "monte-patria", "nombre": "Monte Patria", "regionId": "coquimbo"},
    {"id": "punitaqui", "nombre": "Punitaqui", "regionId": "coquimbo"},
    {"id": "rio-hurtado", "nombre": "Río Hurtado", "regionId": "coquimbo"},
    {"id": "valparaiso", "nombre": "Valparaíso", "regionId": "valparaiso"},
    {"id": "casablanca", "nombre": "Casablanca", "regionId": "valparaiso"},
    {"id": "concon", "nombre": "Concón", "regionId": "valparaiso"},
    {"id": "juan-fernandez", "nombre": "Juan Fernández", "regionId": "valparaiso"},
    {"id": "puchuncavi", "nombre": "Puchuncaví", "regionId": "valparaiso"},
    {"id": "quintero", "nombre": "Quintero", "regionId": "valparaiso"},
    {"id": "vina-del-mar", "nombre": "Viña del Mar", "regionId": "valparaiso"},
    {"id": "isla-de-pascua", "nombre": "Isla de Pascua", "regionId": "valparaiso"},
    {"id": "los-andes", "nombre": "Los Andes", "regionId": "valparaiso"},
    {"id": "calle-larga", "nombre": "Calle Larga", "regionId": "valparaiso"},
    {"id": "rinconada", "nombre": "Rinconada", "regionId": "valparaiso"},
    {"id": "san-esteban", "nombre": "San Esteban", "regionId": "valparaiso"},
    {"id": "la-ligua", "nombre": "La Ligua", "regionId": "valparaiso"},
    {"id": "cabildo", "nombre": "Cabildo", "regionId": "valparaiso"},
    {"id": "papudo", "nombre": "Papudo", "regionId": "valparaiso"},
    {"id": "petorca", "nombre": "Petorca", "regionId": "valparaiso"},
    {"id": "zapallar", "nombre": "Zapallar", "regionId": "valparaiso"},
    {"id": "quillota", "nombre": "Quillota", "regionId": "valparaiso"},
    {"id": "calera", "nombre": "Calera", "regionId": "valparaiso"},
    {"id": "hijuelas", "nombre": "Hijuelas", "regionId": "valparaiso"},
    {"id": "la-cruz", "nombre": "La Cruz", "regionId": "valparaiso"},
    {"id": "nogales", "nombre": "Nogales", "regionId": "valparaiso"},
    {"id": "san-antonio", "nombre": "San Antonio", "regionId": "valparaiso"},
    {"id": "algarrobo", "nombre": "Algarrobo", "regionId": "valparaiso"},
    {"id": "cartagena", "nombre": "Cartagena", "regionId": "valparaiso"},
    {"id": "el-quisco", "nombre": "El Quisco", "regionId": "valparaiso"},
    {"id": "el-tabo", "nombre": "El Tabo", "regionId": "valparaiso"},
    {"id": "santo-domingo", "nombre": "Santo Domingo", "regionId": "valparaiso"},
    {"id": "san-felipe", "nombre": "San Felipe", "regionId": "valparaiso"},
    {"id": "catemu", "nombre": "Catemu", "regionId": "valparaiso"},
    {"id": "llay-llay", "nombre": "Llay-Llay", "regionId": "valparaiso"},
    {"id": "panquehue", "nombre": "Panquehue", "regionId": "valparaiso"},
    {"id": "putaendo", "nombre": "Putaendo", "regionId": "valparaiso"},
    {"id": "santa-maria", "nombre": "Santa María", "regionId": "valparaiso"},
    {"id": "quilpue", "nombre": "Quilpué", "regionId": "valparaiso"},
    {"id": "limache", "nombre": "Limache", "regionId": "valparaiso"},
    {"id": "olmué", "nombre": "Olmué", "regionId": "valparaiso"},
    {"id": "villa-alemana", "nombre": "Villa Alemana", "regionId": "valparaiso"},
    {"id": "santiago", "nombre": "Santiago", "regionId": "metropolitana"},
    {"id": "cerrillos", "nombre": "Cerrillos", "regionId": "metropolitana"},
    {"id": "cerro-navia", "nombre": "Cerro Navia", "regionId": "metropolitana"},
    {"id": "conchali", "nombre": "Conchalí", "regionId": "metropolitana"},
    {"id": "el-bosque", "nombre": "El Bosque", "regionId": "metropolitana"},
    {"id": "estacion-central", "nombre": "Estación Central", "regionId": "metropolitana"},
    {"id": "huechuraba", "nombre": "Huechuraba", "regionId": "metropolitana"},
    {"id": "independencia", "nombre": "Independencia", "regionId": "metropolitana"},
    {"id": "la-cisterna", "nombre": "La Cisterna", "regionId": "metropolitana"},
    {"id": "la-florida", "nombre": "La Florida", "regionId": "metropolitana"},
    {"id": "la-granja", "nombre": "La Granja", "regionId": "metropolitana"},
    {"id": "la-pintana", "nombre": "La Pintana", "regionId": "metropolitana"},
    {"id": "la-reina", "nombre": "La Reina", "regionId": "metropolitana"},
    {"id": "las-condes", "nombre": "Las Condes", "regionId": "metropolitana"},
    {"id": "lo-barnechea", "nombre": "Lo Barnechea", "regionId": "metropolitana"},
    {"id": "lo-espejo", "nombre": "Lo Espejo", "regionId": "metropolitana"},
    {"id": "lo-prado", "nombre": "Lo Prado", "regionId": "metropolitana"},
    {"id": "macul", "nombre": "Macul", "regionId": "metropolitana"},
    {"id": "maipu", "nombre": "Maipú", "regionId": "metropolitana"},
    {"id": "nunoa", "nombre": "Ñuñoa", "regionId": "metropolitana"},
    {"id": "pedro-aguirre-cerda", "nombre": "Pedro Aguirre Cerda", "regionId": "metropolitana"},
    {"id": "penalolen", "nombre": "Peñalolén", "regionId": "metropolitana"},
    {"id": "providencia", "nombre": "Providencia", "regionId": "metropolitana"},
    {"id": "pudahuel", "nombre": "Pudahuel", "regionId": "metropolitana"},
    {"id": "quilicura", "nombre": "Quilicura", "regionId": "metropolitana"},
    {"id": "quinta-normal", "nombre": "Quinta Normal", "regionId": "metropolitana"},
    {"id": "recoleta", "nombre": "Recoleta", "regionId": "metropolitana"},
    {"id": "renca", "nombre": "Renca", "regionId": "metropolitana"},
    {"id": "san-joaquin", "nombre": "San Joaquín", "regionId": "metropolitana"},
    {"id": "san-miguel", "nombre": "San Miguel", "regionId": "metropolitana"},
    {"id": "san-ramon", "nombre": "San Ramón", "regionId": "metropolitana"},
    {"id": "vitacura", "nombre": "Vitacura", "regionId": "metropolitana"},
    {"id": "puente-alto", "nombre": "Puente Alto", "regionId": "metropolitana"},
    {"id": "pirque", "nombre": "Pirque", "regionId": "metropolitana"},
    {"id": "san-jose-de-maipo", "nombre": "San José de Maipo", "regionId": "metropolitana"},
    {"id": "colina", "nombre": "Colina", "regionId": "metropolitana"},
    {"id": "lampa", "nombre": "Lampa", "regionId": "metropolitana"},
    {"id": "tiltil", "nombre": "Tiltil", "regionId": "metropolitana"},
    {"id": "san-bernardo", "nombre": "San Bernardo", "regionId": "metropolitana"},
    {"id": "buin", "nombre": "Buin", "regionId": "metropolitana"},
    {"id": "calera-de-tango", "nombre": "Calera de Tango", "regionId": "metropolitana"},
    {"id": "paine", "nombre": "Paine", "regionId": "metropolitana"},
    {"id": "melipilla", "nombre": "Melipilla", "regionId": "metropolitana"},
    {"id": "alhue", "nombre": "Alhué", "regionId": "metropolitana"},
    {"id": "curacavi", "nombre": "Curacaví", "regionId": "metropolitana"},
    {"id": "maria-pinto", "nombre": "María Pinto", "regionId": "metropolitana"},
    {"id": "san-pedro", "nombre": "San Pedro", "regionId": "metropolitana"},
    {"id": "talagante", "nombre": "Talagante", "regionId": "metropolitana"},
    {"id": "el-monte", "nombre": "El Monte", "regionId": "metropolitana"},
    {"id": "isla-de-maipo", "nombre": "Isla de Maipo", "regionId": "metropolitana"},
    {"id": "padre-hurtado", "nombre": "Padre Hurtado", "regionId": "metropolitana"},
    {"id": "penaflor", "nombre": "Peñaflor", "regionId": "metropolitana"},
    {"id": "rancagua", "nombre": "Rancagua", "regionId": "ohiggins"},
    {"id": "codegua", "nombre": "Codegua", "regionId": "ohiggins"},
    {"id": "coinco", "nombre": "Coinco", "regionId": "ohiggins"},
    {"id": "coltauco", "nombre": "Coltauco", "regionId": "ohiggins"},
    {"id": "donihue", "nombre": "Doñihue", "regionId": "ohiggins"},
    {"id": "graneros", "nombre": "Graneros", "regionId": "ohiggins"},
    {"id": "las-cabras", "nombre": "Las Cabras", "regionId": "ohiggins"},
    {"id": "machali", "nombre": "Machalí", "regionId": "ohiggins"},
    {"id": "malloa", "nombre": "Malloa", "regionId": "ohiggins"},
    {"id": "mostazal", "nombre": "Mostazal", "regionId": "ohiggins"},
    {"id": "olivar", "nombre": "Olivar", "regionId": "ohiggins"},
    {"id": "peumo", "nombre": "Peumo", "regionId": "ohiggins"},
    {"id": "pichidegua", "nombre": "Pichidegua", "regionId": "ohiggins"},
    {"id": "quinta-de-tilcoco", "nombre": "Quinta de Tilcoco", "regionId": "ohiggins"},
    {"id": "renqo", "nombre": "Rengo", "regionId": "ohiggins"},
    {"id": "requinoa", "nombre": "Requínoa", "regionId": "ohiggins"},
    {"id": "san-vicente", "nombre": "San Vicente", "regionId": "ohiggins"},
    {"id": "pichilemu", "nombre": "Pichilemu", "regionId": "ohiggins"},
    {"id": "la-estrella", "nombre": "La Estrella", "regionId": "ohiggins"},
    {"id": "litueche", "nombre": "Litueche", "regionId": "ohiggins"},
    {"id": "marchihue", "nombre": "Marchihue", "regionId": "ohiggins"},
    {"id": "navidad", "nombre": "Navidad", "regionId": "ohiggins"},
    {"id": "paredones", "nombre": "Paredones", "regionId": "ohiggins"},
    {"id": "san-fernando", "nombre": "San Fernando", "regionId": "ohiggins"},
    {"id": "chepica", "nombre": "Chépica", "regionId": "ohiggins"},
    {"id": "chimbarongo", "nombre": "Chimbarongo", "regionId": "ohiggins"},
    {"id": "lolol", "nombre": "Lolol", "regionId": "ohiggins"},
    {"id": "nancagua", "nombre": "Nancagua", "regionId": "ohiggins"},
    {"id": "palmilla", "nombre": "Palmilla", "regionId": "ohiggins"},
    {"id": "peralillo", "nombre": "Peralillo", "regionId": "ohiggins"},
    {"id": "placilla", "nombre": "Placilla", "regionId": "ohiggins"},
    {"id": "pumanque", "nombre": "Pumanque", "regionId": "ohiggins"},
    {"id": "santa-cruz", "nombre": "Santa Cruz", "regionId": "ohiggins"},
    {"id": "talca", "nombre": "Talca", "regionId": "maule"},
    {"id": "constitucion", "nombre": "Constitución", "regionId": "maule"},
    {"id": "curepto", "nombre": "Curepto", "regionId": "maule"},
    {"id": "empedrado", "nombre": "Empedrado", "regionId": "maule"},
    {"id": "maule", "nombre": "Maule", "regionId": "maule"},
    {"id": "pelarco", "nombre": "Pelarco", "regionId": "maule"},
    {"id": "pencahue", "nombre": "Pencahue", "regionId": "maule"},
    {"id": "rio-claro", "nombre": "Río Claro", "regionId": "maule"},
    {"id": "san-clemente", "nombre": "San Clemente", "regionId": "maule"},
    {"id": "san-rafael", "nombre": "San Rafael", "regionId": "maule"},
    {"id": "cauquenes", "nombre": "Cauquenes", "regionId": "maule"},
    {"id": "chanco", "nombre": "Chanco", "regionId": "maule"},
    {"id": "pelluhue", "nombre": "Pelluhue", "regionId": "maule"},
    {"id": "curico", "nombre": "Curicó", "regionId": "maule"},
    {"id": "hualane", "nombre": "Hualañé", "regionId": "maule"},
    {"id": "licanten", "nombre": "Licantén", "regionId": "maule"},
    {"id": "molina", "nombre": "Molina", "regionId": "maule"},
    {"id": "rauco", "nombre": "Rauco", "regionId": "maule"},
    {"id": "romeral", "nombre": "Romeral", "regionId": "maule"},
    {"id": "sagrada-familia", "nombre": "Sagrada Familia", "regionId": "maule"},
    {"id": "teno", "nombre": "Teno", "regionId": "maule"},
    {"id": "vichuquen", "nombre": "Vichuquén", "regionId": "maule"},
    {"id": "linares", "nombre": "Linares", "regionId": "maule"},
    {"id": "colbun", "nombre": "Colbún", "regionId": "maule"},
    {"id": "longavi", "nombre": "Longaví", "regionId": "maule"},
    {"id": "parral", "nombre": "Parral", "regionId": "maule"},
    {"id": "retiro", "nombre": "Retiro", "regionId": "maule"},
    {"id": "san-javier", "nombre": "San Javier", "regionId": "maule"},
    {"id": "villa-alegre", "nombre": "Villa Alegre", "regionId": "maule"},
    {"id": "yerbas-buenas", "nombre": "Yerbas Buenas", "regionId": "maule"},
    {"id": "chillan", "nombre": "Chillán", "regionId": "nuble"},
    {"id": "bulnes", "nombre": "Bulnes", "regionId": "nuble"},
    {"id": "cobquecura", "nombre": "Cobquecura", "regionId": "nuble"},
    {"id": "coelemu", "nombre": "Coelemu", "regionId": "nuble"},
    {"id": "coihueco", "nombre": "Coihueco", "regionId": "nuble"},
    {"id": "chillan-viejo", "nombre": "Chillán Viejo", "regionId": "nuble"},
    {"id": "el-carmen", "nombre": "El Carmen", "regionId": "nuble"},
    {"id": "ninhue", "nombre": "Ninhue", "regionId": "nuble"},
    {"id": "niquen", "nombre": "Ñiquén", "regionId": "nuble"},
    {"id": "pemuco", "nombre": "Pemuco", "regionId": "nuble"},
    {"id": "pinto", "nombre": "Pinto", "regionId": "nuble"},
    {"id": "portezuelo", "nombre": "Portezuelo", "regionId": "nuble"},
    {"id": "quillon", "nombre": "Quillón", "regionId": "nuble"},
    {"id": "quirihue", "nombre": "Quirihue", "regionId": "nuble"},
    {"id": "ranquil", "nombre": "Ránquil", "regionId": "nuble"},
    {"id": "san-carlos", "nombre": "San Carlos", "regionId": "nuble"},
    {"id": "san-fabian", "nombre": "San Fabián", "regionId": "nuble"},
    {"id": "san-ignacio", "nombre": "San Ignacio", "regionId": "nuble"},
    {"id": "san-nicolas", "nombre": "San Nicolás", "regionId": "nuble"},
    {"id": "trehuaco", "nombre": "Trehuaco", "regionId": "nuble"},
    {"id": "yungay", "nombre": "Yungay", "regionId": "nuble"},
    {"id": "concepcion", "nombre": "Concepción", "regionId": "biobio"},
    {"id": "coronel", "nombre": "Coronel", "regionId": "biobio"},
    {"id": "chiguayante", "nombre": "Chiguayante", "regionId": "biobio"},
    {"id": "florida", "nombre": "Florida", "regionId": "biobio"},
    {"id": "hualqui", "nombre": "Hualqui", "regionId": "biobio"},
    {"id": "lota", "nombre": "Lota", "regionId": "biobio"},
    {"id": "penco", "nombre": "Penco", "regionId": "biobio"},
    {"id": "san-pedro-de-la-paz", "nombre": "San Pedro de la Paz", "regionId": "biobio"},
    {"id": "santa-juana", "nombre": "Santa Juana", "regionId": "biobio"},
    {"id": "talcahuano", "nombre": "Talcahuano", "regionId": "biobio"},
    {"id": "tome", "nombre": "Tomé", "regionId": "biobio"},
    {"id": "hualpen", "nombre": "Hualpén", "regionId": "biobio"},
    {"id": "lebu", "nombre": "Lebu", "regionId": "biobio"},
    {"id": "arauco", "nombre": "Arauco", "regionId": "biobio"},
    {"id": "canete", "nombre": "Cañete", "regionId": "biobio"},
    {"id": "contulmo", "nombre": "Contulmo", "regionId": "biobio"},
    {"id": "curanilahue", "nombre": "Curanilahue", "regionId": "biobio"},
    {"id": "los-alamos", "nombre": "Los Álamos", "regionId": "biobio"},
    {"id": "tirua", "nombre": "Tirúa", "regionId": "biobio"},
    {"id": "los-angeles", "nombre": "Los Ángeles", "regionId": "biobio"},
    {"id": "antuco", "nombre": "Antuco", "regionId": "biobio"},
    {"id": "cabrero", "nombre": "Cabrero", "regionId": "biobio"},
    {"id": "laja", "nombre": "Laja", "regionId": "biobio"},
    {"id": "mulchen", "nombre": "Mulchén", "regionId": "biobio"},
    {"id": "nacimiento", "nombre": "Nacimiento", "regionId": "biobio"},
    {"id": "negrete", "nombre": "Negrete", "regionId": "biobio"},
    {"id": "quilleco", "nombre": "Quilleco", "regionId": "biobio"},
    {"id": "san-rosendo", "nombre": "San Rosendo", "regionId": "biobio"},
    {"id": "santa-barbara", "nombre": "Santa Bárbara", "regionId": "biobio"},
    {"id": "tucapel", "nombre": "Tucapel", "regionId": "biobio"},
    {"id": "yumbel", "nombre": "Yumbel", "regionId": "biobio"},
    {"id": "alto-biobio", "nombre": "Alto Biobío", "regionId": "biobio"},
    {"id": "temuco", "nombre": "Temuco", "regionId": "araucania"},
    {"id": "carahue", "nombre": "Carahue", "regionId": "araucania"},
    {"id": "cunco", "nombre": "Cunco", "regionId": "araucania"},
    {"id": "curarrehue", "nombre": "Curarrehue", "regionId": "araucania"},
    {"id": "freire", "nombre": "Freire", "regionId": "araucania"},
    {"id": "galvarino", "nombre": "Galvarino", "regionId": "araucania"},
    {"id": "gorbea", "nombre": "Gorbea", "regionId": "araucania"},
    {"id": "lautaro", "nombre": "Lautaro", "regionId": "araucania"},
    {"id": "loncoche", "nombre": "Loncoche", "regionId": "araucania"},
    {"id": "melipeuco", "nombre": "Melipeuco", "regionId": "araucania"},
    {"id": "nueva-imperial", "nombre": "Nueva Imperial", "regionId": "araucania"},
    {"id": "padre-las-casas", "nombre": "Padre Las Casas", "regionId": "araucania"},
    {"id": "perquenco", "nombre": "Perquenco", "regionId": "araucania"},
    {"id": "pitrufquen", "nombre": "Pitrufquén", "regionId": "araucania"},
    {"id": "pucon", "nombre": "Pucón", "regionId": "araucania"},
    {"id": "saavedra", "nombre": "Saavedra", "regionId": "araucania"},
    {"id": "teodoro-schmidt", "nombre": "Teodoro Schmidt", "regionId": "araucania"},
    {"id": "tolten", "nombre": "Toltén", "regionId": "araucania"},
    {"id": "vilcun", "nombre": "Vilcún", "regionId": "araucania"},
    {"id": "villarrica", "nombre": "Villarrica", "regionId": "araucania"},
    {"id": "cholchol", "nombre": "Cholchol", "regionId": "araucania"},
    {"id": "angol", "nombre": "Angol", "regionId": "araucania"},
    {"id": "collipulli", "nombre": "Collipulli", "regionId": "araucania"},
    {"id": "curacautin", "nombre": "Curacautín", "regionId": "araucania"},
    {"id": "ercilla", "nombre": "Ercilla", "regionId": "araucania"},
    {"id": "lonquimay", "nombre": "Lonquimay", "regionId": "araucania"},
    {"id": "los-sauces", "nombre": "Los Sauces", "regionId": "araucania"},
    {"id": "lumaco", "nombre": "Lumaco", "regionId": "araucania"},
    {"id": "puren", "nombre": "Purén", "regionId": "araucania"},
    {"id": "renaico", "nombre": "Renaico", "regionId": "araucania"},
    {"id": "traiguen", "nombre": "Traiguén", "regionId": "araucania"},
    {"id": "victoria", "nombre": "Victoria", "regionId": "araucania"},
    {"id": "valdivia", "nombre": "Valdivia", "regionId": "los-rios"},
    {"id": "corral", "nombre": "Corral", "regionId": "los-rios"},
    {"id": "lanco", "nombre": "Lanco", "regionId": "los-rios"},
    {"id": "los-lagos", "nombre": "Los Lagos", "regionId": "los-rios"},
    {"id": "mafil", "nombre": "Máfil", "regionId": "los-rios"},
    {"id": "mariquina", "nombre": "Mariquina", "regionId": "los-rios"},
    {"id": "paillaco", "nombre": "Paillaco", "regionId": "los-rios"},
    {"id": "panguipulli", "nombre": "Panguipulli", "regionId": "los-rios"},
    {"id": "la-union", "nombre": "La Unión", "regionId": "los-rios"},
    {"id": "futrono", "nombre": "Futrono", "regionId": "los-rios"},
    {"id": "lago-ranco", "nombre": "Lago Ranco", "regionId": "los-rios"},
    {"id": "rio-bueno", "nombre": "Río Bueno", "regionId": "los-rios"},
    {"id": "puerto-montt", "nombre": "Puerto Montt", "regionId": "los-lagos"},
    {"id": "calbuco", "nombre": "Calbuco", "regionId": "los-lagos"},
    {"id": "cochamo", "nombre": "Cochamó", "regionId": "los-lagos"},
    {"id": "fresia", "nombre": "Fresia", "regionId": "los-lagos"},
    {"id": "frutillar", "nombre": "Frutillar", "regionId": "los-lagos"},
    {"id": "los-muermos", "nombre": "Los Muermos", "regionId": "los-lagos"},
    {"id": "llanquihue", "nombre": "Llanquihue", "regionId": "los-lagos"},
    {"id": "maullin", "nombre": "Maullín", "regionId": "los-lagos"},
    {"id": "puerto-varas", "nombre": "Puerto Varas", "regionId": "los-lagos"},
    {"id": "castro", "nombre": "Castro", "regionId": "los-lagos"},
    {"id": "ancud", "nombre": "Ancud", "regionId": "los-lagos"},
    {"id": "chacao", "nombre": "Chacao", "regionId": "los-lagos"},
    {"id": "chonchi", "nombre": "Chonchi", "regionId": "los-lagos"},
    {"id": "curaco-de-velez", "nombre": "Curaco de Vélez", "regionId": "los-lagos"},
    {"id": "dalcahue", "nombre": "Dalcahue", "regionId": "los-lagos"},
    {"id": "puqueldon", "nombre": "Puqueldón", "regionId": "los-lagos"},
    {"id": "queilen", "nombre": "Queilén", "regionId": "los-lagos"},
    {"id": "quellon", "nombre": "Quellón", "regionId": "los-lagos"},
    {"id": "quemchi", "nombre": "Quemchi", "regionId": "los-lagos"},
    {"id": "quinchao", "nombre": "Quinchao", "regionId": "los-lagos"},
    {"id": "osorno", "nombre": "Osorno", "regionId": "los-lagos"},
    {"id": "puerto-octay", "nombre": "Puerto Octay", "regionId": "los-lagos"},
    {"id": "purranque", "nombre": "Purranque", "regionId": "los-lagos"},
    {"id": "puyehue", "nombre": "Puyehue", "regionId": "los-lagos"},
    {"id": "rio-negro", "nombre": "Río Negro", "regionId": "los-lagos"},
    {"id": "san-juan-de-la-costa", "nombre": "San Juan de la Costa", "regionId": "los-lagos"},
    {"id": "san-pablo", "nombre": "San Pablo", "regionId": "los-lagos"},
    {"id": "chaiten", "nombre": "Chaitén", "regionId": "los-lagos"},
    {"id": "futaleufu", "nombre": "Futaleufú", "regionId": "los-lagos"},
    {"id": "hualaihue", "nombre": "Hualaihué", "regionId": "los-lagos"},
    {"id": "palena", "nombre": "Palena", "regionId": "los-lagos"},
    {"id": "coihaique", "nombre": "Coyhaique", "regionId": "aysen"},
    {"id": "lago-verde", "nombre": "Lago Verde", "regionId": "aysen"},
    {"id": "aisen", "nombre": "Aisén", "regionId": "aysen"},
    {"id": "cisnes", "nombre": "Cisnes", "regionId": "aysen"},
    {"id": "guaitecas", "nombre": "Guaitecas", "regionId": "aysen"},
    {"id": "chile-chico", "nombre": "Chile Chico", "regionId": "aysen"},
    {"id": "rio-ibanez", "nombre": "Río Ibáñez", "regionId": "aysen"},
    {"id": "cochrane", "nombre": "Cochrane", "regionId": "aysen"},
    {"id": "ohiggins-aysen", "nombre": "O'Higgins", "regionId": "aysen"},
    {"id": "tortel", "nombre": "Tortel", "regionId": "aysen"},
    {"id": "punta-arenas", "nombre": "Punta Arenas", "regionId": "magallanes"},
    {"id": "laguna-blanca", "nombre": "Laguna Blanca", "regionId": "magallanes"},
    {"id": "rio-verde", "nombre": "Río Verde", "regionId": "magallanes"},
    {"id": "san-gregorio", "nombre": "San Gregorio", "regionId": "magallanes"},
    {"id": "porvenir", "nombre": "Porvenir", "regionId": "magallanes"},
    {"id": "primavera", "nombre": "Primavera", "regionId": "magallanes"},
    {"id": "timaukel", "nombre": "Timaukel", "regionId": "magallanes"},
    {"id": "natales", "nombre": "Natales", "regionId": "magallanes"},
    {"id": "torres-del-paine", "nombre": "Torres del Paine", "regionId": "magallanes"},
    {"id": "cabo-de-hornos", "nombre": "Cabo de Hornos", "regionId": "magallanes"},
    {"id": "antartica", "nombre": "Antártica", "regionId": "magallanes"}
]

# Datos para carreras
carreras_data = [
    {"id": "ing-civil-usach", "nombre": "Ingeniería Civil", "casaEstudioId": "usach", "duracionAnios": 6, "area": "Ingeniería"},
    {"id": "ing-informatica-usach", "nombre": "Ingeniería en Informática", "casaEstudioId": "usach", "duracionAnios": 5, "area": "Tecnología"},
    {"id": "medicina-uchile", "nombre": "Medicina", "casaEstudioId": "uchile", "duracionAnios": 7, "area": "Salud"},
    {"id": "derecho-puc", "nombre": "Derecho", "casaEstudioId": "puc", "duracionAnios": 5, "area": "Ciencias Sociales"},
    {"id": "arquitectura-uaustral", "nombre": "Arquitectura", "casaEstudioId": "uaustral", "duracionAnios": 6, "area": "Arte y Diseño"},
    {"id": "ing-comercial-ucv", "nombre": "Ingeniería Comercial", "casaEstudioId": "ucv", "duracionAnios": 5, "area": "Negocios"},
    {"id": "biologia-udec", "nombre": "Biología", "casaEstudioId": "udec", "duracionAnios": 5, "area": "Ciencias"},
    {"id": "diseno-grafico-duocuc", "nombre": "Diseño Gráfico", "casaEstudioId": "duocuc", "duracionAnios": 4, "area": "Arte y Diseño"},
    {"id": "tecnico-mecanica-inacap", "nombre": "Técnico en Mecánica Automotriz", "casaEstudioId": "inacap", "duracionAnios": 3, "area": "Técnica"},
    {"id": "periodismo-udp", "nombre": "Periodismo", "casaEstudioId": "udp", "duracionAnios": 5, "area": "Comunicación"},
    {"id": "pedagogia-utalca", "nombre": "Pedagogía en Educación Básica", "casaEstudioId": "utalca", "duracionAnios": 5, "area": "Educación"}
]

# Función para subir datos a una colección
def upload_collection(collection_name, data):
    try:
        for item in data:
            doc_ref = db.collection(collection_name).document(item["id"])
            doc_ref.set(item)
        print(f"Colección '{collection_name}' subida con éxito!")
    except Exception as e:
        print(f"Error al subir la colección '{collection_name}': {e}")

# Subir todas las colecciones
def upload_all_data():
    upload_collection("casaEstudios", casa_estudios_data)
    upload_collection("regiones", regiones_data)
    upload_collection("comunas", comunas_data)
    upload_collection("carreras", carreras_data)

# Ejecutar la función
if __name__ == "__main__":
    upload_all_data()